In [2]:
import numpy as np
import pandas as pd
from scipy.linalg import svd, lu

In [3]:
# define a matrix
X = np.array([[3, 3, 2], [2, 3, -2]])
print(X)
# perform SVD
U, singular, V_transpose = svd(X)
# print different components
print("U: ", U)
print("Singular array", singular)
print("V^{T}", V_transpose)

[[ 3  3  2]
 [ 2  3 -2]]
U:  [[-0.7815437 -0.6238505]
 [-0.6238505  0.7815437]]
Singular array [5.54801894 2.86696457]
V^{T} [[-0.64749817 -0.7599438  -0.05684667]
 [-0.10759258  0.16501062 -0.9804057 ]
 [-0.75443354  0.62869461  0.18860838]]


## Solar

In [4]:
dat = pd.read_csv('solar_clean_data.csv')

In [5]:
dat.drop('Date',axis=1,inplace=True)

In [6]:
arr = np.array(dat)
arr

array([[3.21800000e+03, 9.37535974e+00, 1.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [3.63300000e+03, 9.37535974e+00, 1.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [4.37700000e+03, 9.37535974e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       ...,
       [3.73203000e+03, 5.83400000e+00, 1.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [4.06388000e+03, 5.58400000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [4.09390000e+03, 5.63500000e+00, 1.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00]])

## SVD

In [7]:
U, singular, V_transpose = svd(arr)
# print different components
print("U: ", U)
print("Singular array", singular)
print("V^{T}", V_transpose)

U:  [[-1.60203596e-02  6.30026229e-04 -2.52921673e-02 ... -1.97310808e-02
  -1.70946686e-02 -2.14911270e-02]
 [-1.80863663e-02  4.41278478e-04 -2.36053543e-02 ... -3.54638856e-04
   9.72367648e-04 -1.74688758e-04]
 [-2.17902431e-02  1.02909252e-04  1.28992118e-02 ...  2.81197622e-02
  -1.73223713e-02  2.68354413e-02]
 ...
 [-1.85793347e-02 -3.94599124e-04 -3.19790129e-02 ...  9.97991307e-01
   4.76267180e-04 -1.97750901e-03]
 [-2.02313901e-02 -6.01330398e-04  1.16271714e-02 ...  4.40778401e-04
   9.94982183e-01  3.90596739e-04]
 [-2.03808408e-02 -6.03621432e-04 -3.05081174e-02 ... -1.98050289e-03
   4.34713751e-04  9.98043747e-01]]
Singular array [2.00870178e+05 4.47805769e+03 2.49051227e+01 2.35654742e+01
 1.89070797e+01 1.40816316e+01 8.02735449e+00 7.53075785e+00
 5.86195666e+00 5.07809263e+00 4.32518018e+00 9.99037536e-01]
V^{T} [[-9.99997919e-01 -2.03668635e-03 -8.02168012e-05 -1.75631018e-05
  -8.24029817e-05 -2.14323077e-06 -1.56964976e-06 -6.84519127e-06
  -1.18261258e-07 -6.51

# QR

In [8]:
# Decomposition of the said matrix
q, r = np.linalg.qr(arr)
print('\nQ:\n', q)
print('\nR:\n', r)


Q:
 [[-0.01602033 -0.00063075  0.03032787 ... -0.00530272 -0.00133927
  -0.00781083]
 [-0.01808635 -0.0004421   0.0289669  ... -0.00584681 -0.00152048
  -0.00846371]
 [-0.02179024 -0.00010388 -0.01435352 ... -0.0019278  -0.01092505
  -0.01464462]
 ...
 [-0.01857935  0.00039374  0.02864194 ... -0.00056561  0.00049665
  -0.00441772]
 [-0.02023142  0.00060043 -0.01332689 ... -0.00151869 -0.01079128
  -0.01414882]
 [-0.02038087  0.00060268  0.0274552  ... -0.00104011  0.00033849
  -0.00498684]]

R:
 [[-2.00869760e+05 -4.08906225e+02 -1.61131632e+01 -3.52789250e+00
  -1.65523142e+01 -4.30511093e-01 -3.15295741e-01 -1.37499631e+00
  -2.37551934e-02 -1.30844309e+00 -4.73245848e-01 -5.77093042e+00]
 [ 0.00000000e+00 -4.47806696e+03  6.22264014e-03 -2.39554037e-01
   2.81581975e-01 -9.71957888e-04 -1.82916574e-03  3.36766548e-02
   7.44662037e-04  7.09301081e-03  5.29461827e-03 -1.22753618e-01]
 [ 0.00000000e+00  0.00000000e+00  2.44615194e+01  2.09128396e+00
   1.52435780e+00  4.11385343e-01 

# LU

Returns:
(If permute_l == False)

p(M, M) ndarray

Permutation matrix

l(M, K) ndarray

Lower triangular or trapezoidal matrix with unit diagonal. K = min(M, N)

u(K, N) ndarray

Upper triangular or trapezoidal matrix

(If permute_l == True)

pl(M, K) ndarray

Permuted L matrix. K = min(M, N)

u(K, N) ndarray

Upper triangular or trapezoidal matrix

In [9]:
# Decomposition of the said matrix
p,l,u = lu(arr)
print('\np:\n', p)
print('\nl:\n', l)
print('\nu:\n', u)


p:
 [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]

l:
 [[ 1.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 6.67217547e-01  1.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 1.28086093e-01  2.35427450e-01  1.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 ...
 [ 6.07057228e-01  3.27572353e-04  3.82082756e-01 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 6.61036413e-01  1.75180293e-04 -6.42296008e-01 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 6.65919509e-01  1.78776733e-04  3.24782627e-01 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]]

u:
 [[ 6.14774000e+03  7.32500000e+00  1.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000

In [10]:
# permute_l == True
pl,u = lu(arr,permute_l=True)
# print('\np:\n', p)
print('\npl:\n', pl)
print('\nu:\n', u)


pl:
 [[ 5.23444388e-01  1.30837833e-03  4.63975508e-01 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 5.90948869e-01  1.19162339e-03  3.98297475e-01 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 7.11968951e-01  9.82308509e-04 -6.91270003e-01 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 ...
 [ 6.07057228e-01  3.27572353e-04  3.82082756e-01 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 6.61036413e-01  1.75180293e-04 -6.42296008e-01 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 6.65919509e-01  1.78776733e-04  3.24782627e-01 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]]

u:
 [[ 6.14774000e+03  7.32500000e+00  1.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  4.23511263e+03 -6.67217547e-01  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.0

# NMF

In [11]:
from sklearn.decomposition import NMF

In [12]:
X = np.array([[1, 1], [2, 1], [3, 1.2], [4, 1], [5, 0.8], [6, 1]])
X

array([[1. , 1. ],
       [2. , 1. ],
       [3. , 1.2],
       [4. , 1. ],
       [5. , 0.8],
       [6. , 1. ]])

In [13]:
model = NMF(n_components=2, init='random', random_state=0)
W = model.fit_transform(arr)
H = model.components_

In [14]:
H

array([[1.39849422e+02, 2.57326088e-01, 9.12477726e-03, 1.14515393e-03,
        9.93052294e-03, 0.00000000e+00, 2.16478338e-04, 7.40577222e-04,
        1.83521909e-05, 7.37564733e-04, 2.29846208e-04, 1.71181337e-03],
       [1.54325493e+02, 7.04755771e-01, 3.30612081e-02, 2.11934341e-02,
        2.48450150e-02, 5.42239713e-03, 2.60090692e-05, 3.44411123e-03,
        0.00000000e+00, 2.74026410e-03, 1.59529460e-03, 3.73086063e-02]])

In [15]:
W

array([[1.80531544e+01, 4.49235366e+00],
       [2.59778353e+01, 1.72529292e-04],
       [2.66395089e+01, 4.22145195e+00],
       ...,
       [2.58182923e+01, 7.86322616e-01],
       [2.61473557e+01, 2.63840039e+00],
       [2.39757188e+01, 4.80083498e+00]])

## SVD scratch

In [16]:
import numpy as np

In [17]:
a = np.array([[3,2,2],[2,3,-2]])
a

array([[ 3,  2,  2],
       [ 2,  3, -2]])

In [18]:
at = a.T
at

array([[ 3,  2],
       [ 2,  3],
       [ 2, -2]])

In [19]:
A = np.dot(a,at)
A

array([[17,  8],
       [ 8, 17]])

In [20]:
B = np.dot(at,a)
B

array([[13, 12,  2],
       [12, 13, -2],
       [ 2, -2,  8]])

In [21]:
np.linalg.eig(A)

(array([25.,  9.]),
 array([[ 0.70710678, -0.70710678],
        [ 0.70710678,  0.70710678]]))

In [22]:
np.linalg.eig(B)

(array([2.5000000e+01, 5.0324328e-15, 9.0000000e+00]),
 array([[-7.07106781e-01, -6.66666667e-01,  2.35702260e-01],
        [-7.07106781e-01,  6.66666667e-01, -2.35702260e-01],
        [-4.59701721e-17,  3.33333333e-01,  9.42809042e-01]]))

In [51]:
c = np.array([[-4,-7],[1,4]])
print('c:\n',c)
ct = c.T
print('ct:\n',ct)
np.dot(c,ct)

c:
 [[-4 -7]
 [ 1  4]]
ct:
 [[-4  1]
 [-7  4]]


array([[ 65, -32],
       [-32,  17]])

In [61]:
C = np.array([[65,-32],[-32,17]])
w,h = np.linalg.eig(C)
print(w)
print(h)

[81.  1.]
[[ 0.89442719  0.4472136 ]
 [-0.4472136   0.89442719]]


In [62]:
wd = np.diag(w)
wd

array([[81.,  0.],
       [ 0.,  1.]])

In [77]:
len(w)

In [74]:
kk=[]
for i in range(len(h)):
    kk.append(np.dot(ct,h[i])/np.sqrt(w[i]))
np.array(kk)

array([[-0.3478328 , -0.49690399],
       [ 2.68328157,  6.70820393]])

In [24]:
np.sqrt(5)

2.23606797749979

In [25]:
0.894*2.236

1.9989840000000003

In [26]:
-2/2.236

-0.8944543828264757

In [27]:
np.linalg.svd(A)

(array([[-0.70710678, -0.70710678],
        [-0.70710678,  0.70710678]]),
 array([25.,  9.]),
 array([[-0.70710678, -0.70710678],
        [-0.70710678,  0.70710678]]))

In [28]:
np.diag((1, 2, 3))

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [29]:
import sympy as sp
sp.init_printing(use_unicode=True)

mat_a = sp.Matrix(C)
xx = mat_a.eigenvects()
xx

⎡⎛      ⎡⎡1/2⎤⎤⎞  ⎛       ⎡⎡-2⎤⎤⎞⎤
⎢⎜1, 1, ⎢⎢   ⎥⎥⎟, ⎜81, 1, ⎢⎢  ⎥⎥⎟⎥
⎣⎝      ⎣⎣ 1 ⎦⎦⎠  ⎝       ⎣⎣1 ⎦⎦⎠⎦

In [30]:
np.array(xx[1][-1][0])

array([[-2],
       [1]], dtype=object)

In [31]:
# ev = np.array([])
ev=[]
ev

In [32]:
for i in range(len(xx)):
    print(xx[i][-1][0])
    vec = np.array(xx[1][-1][0])
    # ev = np.append(ev,np.array(xx[1][-1][0]))
    ev.append(vec)

Matrix([[1/2], [1]])
Matrix([[-2], [1]])


In [33]:
ev

[array([[-2],
        [1]], dtype=object),
 array([[-2],
        [1]], dtype=object)]

### solar eigenvalues eigenvectors 

In [34]:
arr_t = arr.T

In [35]:
arr

array([[3.21800000e+03, 9.37535974e+00, 1.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [3.63300000e+03, 9.37535974e+00, 1.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [4.37700000e+03, 9.37535974e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       ...,
       [3.73203000e+03, 5.83400000e+00, 1.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [4.06388000e+03, 5.58400000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [4.09390000e+03, 5.63500000e+00, 1.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00]])

In [36]:
arr_t

array([[3.21800000e+03, 3.63300000e+03, 4.37700000e+03, ...,
        3.73203000e+03, 4.06388000e+03, 4.09390000e+03],
       [9.37535974e+00, 9.37535974e+00, 9.37535974e+00, ...,
        5.83400000e+00, 5.58400000e+00, 5.63500000e+00],
       [1.00000000e+00, 1.00000000e+00, 0.00000000e+00, ...,
        1.00000000e+00, 0.00000000e+00, 1.00000000e+00],
       ...,
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00]])

In [37]:
AAT = np.dot(arr, arr_t)
AAT

array([[10355612.89737031, 11691082.89737031, 14085273.89737031, ...,
        12009728.23584874, 13077618.1920088 , 13174224.03015215],
       [11691082.89737031, 13198777.89737031, 15901728.89737031, ...,
        13558520.68584874, 14764128.39200881, 14873192.53015215],
       [14085273.89737031, 15901728.89737031, 19158217.89737031, ...,
        16335150.00584874, 17787656.11200881, 17919053.13015215],
       ...,
       [12009728.23584874, 13558520.68584874, 16335150.00584874, ...,
        13928083.956456  , 15166554.653456  , 15278592.49159   ],
       [13077618.1920088 , 14764128.39200881, 17787656.11200881, ...,
        15166554.653456  , 16515152.835456  , 16637149.79784   ],
       [13174224.03015215, 14873192.53015215, 17919053.13015215, ...,
        15278592.49159   , 16637149.79784   , 16760050.963225  ]])

In [38]:
eigenvalue, eigenvector = np.linalg.eig(AAT)
print('eigenvalues are: ----> \n',eigenvalue, '\n normalized eigenvectors are: ----> \n',eigenvector)

eigenvalues are: ----> 
 [ 4.03488285e+10+0.j  2.00530007e+07+0.j  6.20265136e+02+0.j ...
 -3.67312740e-14+0.j -8.05007175e-14+0.j  1.58538123e-23+0.j] 
 normalized eigenvectors are: ----> 
 [[-1.60203596e-02+0.j  6.30026229e-04+0.j  2.52921673e-02+0.j ...
  -3.10049217e-04+0.j  5.78439008e-04+0.j  2.15577248e-14+0.j]
 [-1.80863663e-02+0.j  4.41278478e-04+0.j  2.36053543e-02+0.j ...
  -4.89063537e-06+0.j  8.59653762e-06+0.j  4.25012109e-16+0.j]
 [-2.17902431e-02+0.j  1.02909252e-04+0.j -1.28992114e-02+0.j ...
   7.94609793e-05+0.j -1.45723462e-04+0.j -5.94183296e-15+0.j]
 ...
 [-1.85793347e-02+0.j -3.94599124e-04+0.j  3.19790127e-02+0.j ...
  -1.32265685e-03+0.j  2.46601466e-03+0.j  9.19935614e-14+0.j]
 [-2.02313901e-02+0.j -6.01330398e-04+0.j -1.16271714e-02+0.j ...
   2.86794113e-04+0.j -7.32891795e-04+0.j  1.79517047e-15+0.j]
 [-2.03808408e-02+0.j -6.03621432e-04+0.j  3.05081173e-02+0.j ...
   1.03155519e-04+0.j -2.33478099e-04+0.j -1.04377160e-15+0.j]]


In [78]:
len(eigenvalue)

In [80]:
len(eigenvector)

In [39]:
import sympy as sp
sp.init_printing(use_unicode=True)

In [40]:
# mat_a = sp.Matrix(AAT)
# xx = mat_a.eigenvects()
# xx

In [41]:
# ev = np.array([])
ev=[]
ev
for i in range(len(xx)):
    print(xx[i][-1][0])
    vec = np.array(xx[1][-1][0])
    # ev = np.append(ev,np.array(xx[1][-1][0]))
    ev.append(vec)
print(ev)

Matrix([[1/2], [1]])
Matrix([[-2], [1]])
[array([[-2],
       [1]], dtype=object), array([[-2],
       [1]], dtype=object)]


### MOVING FURTHER


In [43]:
sigma = np.sqrt(eigenvalue)
sigma

array([2.00870178e+05+0.00000000e+00j, 4.47805769e+03+0.00000000e+00j,
       2.49051227e+01+0.00000000e+00j, ...,
       0.00000000e+00+1.91654048e-07j, 0.00000000e+00+2.83726484e-07j,
       3.98168460e-12+0.00000000e+00j])

In [45]:
cc = np.array([1,2,3])
cc

array([1, 2, 3])

In [46]:
cc/np.array([1,2,3])

array([1., 1., 1.])

In [82]:
from tqdm import tqdm

In [83]:
U=[]
for i in tqdm(range(len(eigenvector))):
    U.append(np.dot(AAT,eigenvector[i])/np.sqrt(eigenvalue[i]))
U_final = np.array(U)
U_final

100%|██████████| 2370/2370 [00:49<00:00, 47.79it/s]


array([[ 5.03175195e+00-5.13802520e-01j,  5.68068145e+00-5.80074830e-01j,
         6.84406376e+00-6.98886576e-01j, ...,
         5.83560473e+00-5.95921933e-01j,  6.35451864e+00-6.48918797e-01j,
         6.40145961e+00-6.53711632e-01j],
       [-3.67227913e+01-2.60951557e+00j, -4.14585038e+01-2.94580728e+00j,
        -4.99485459e+01-3.54869749e+00j, ...,
        -4.25881778e+01-3.02536283e+00j, -4.63749998e+01-3.29422236e+00j,
        -4.67175828e+01-3.31856221e+00j],
       [-4.32072908e+04-5.62955596e+03j, -4.87788559e+04-6.35462649e+03j,
        -5.87673974e+04-7.65451239e+03j, ...,
        -5.01068038e+04-6.52492841e+03j, -5.45619328e+04-7.10452981e+03j,
        -5.49649858e+04-7.15701957e+03j],
       ...,
       [ 1.03429931e+13-9.38525143e+13j,  1.16764981e+13-1.05956189e+14j,
         1.40671690e+13-1.27655308e+14j, ...,
         1.19936847e+13-1.08845200e+14j,  1.30599363e+13-1.18523820e+14j,
         1.31564115e+13-1.19399355e+14j],
       [-4.52561958e+12-5.06370862e+13j, -5.

## Finally we have 'U_final' and eigenvalues matrix 

### we can now promote S = eigenvalues , U_final

### now need to regularize it

may use Gradient Descent